# Generated by Django 3.1.4 on 2020-12-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('logo', models.ImageField(blank=True, max_length=200, upload_to='about')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Haqida',
                'verbose_name_plural': 'Haqidalar',
            },
        ),
    ]
