# Generated by Django 3.1.4 on 2020-12-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
