# Generated by Django 3.1.4 on 2020-12-31 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20201231_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.catalog'),
        ),
    ]
