# Generated by Django 3.1.4 on 2021-01-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20210102_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AddField(
            model_name='contact',
            name='office',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
